# URL format: <servername>:<port>
# Secret name: valid K8S name
# append unique progressing number for more certs

# do not set protocol https://
TCERT_ENDPOINT_URL_1=cpd-cp4ba-wfps-authoring-pfs-prod.apps.itz-2agwjr.hub01-lb.techzone.ibm.com:443
TCERT_SECRET_NAME_1=wfps-trusted-cert1

#TCERT_ENDPOINT_URL_2=www.ibm.com:443
#TCERT_SECRET_NAME_2=wfps-trusted-cert2

