# https://www.ibm.com/docs/en/cloud-paks/cp-biz-automation/26.0.0?topic=icpd-installing-cp4ba-workflow-process-service-runtime-production-deployment
# https://www.ibm.com/docs/en/cloud-paks/cp-biz-automation/26.0.0?topic=deployment-customizing-workflow-process-service-runtime#tsk_customize_wfps__liberty
# https://www.ibm.com/docs/en/cloud-paks/cp-biz-automation/26.0.0?topic=reference-cp4ba-workflow-process-service-runtime-parameters

apiVersion: icp4a.ibm.com/v1
kind: WfPSRuntime
metadata:
  name: ${WFPS_NAME}
  namespace: ${WFPS_NAMESPACE}
spec:
  appVersion: "${WFPS_APP_VER}"
  license:
    accept: true
  deploymentLicense: "${WFPS_LICENSE_TYPE}"
  admin:
    username: ${WFPS_ADMINUSER}
  capabilities: 
    federate:
      enable: ${WFPS_FEDERATE}
    fullTextSearch:
      enable: ${WFPS_FEDERATE_TEXTSEARCH}
      esStorage:
        storageClassName: ${WFPS_STORAGE_CLASS_BLOCK}
        size: "${WFPS_FEDERATE_TEXTSEARCH_SIZE}"
      esSnapshotStorage:
        storageClassName: ${WFPS_STORAGE_CLASS_BLOCK}
        size: "${WFPS_FEDERATE_TEXTSEARCHSIZE_SNAP}"
  tls:
    serverTrustCertificateList: [${WFPS_TLS_SECRET_NAMES}]
  persistent:
    data:
      enable: ${WFPS_PERS_DATA_ENABLE}
      size: ${WFPS_PERS_DATA_SIZE}
    storageClassName: ${WFPS_STORAGE_CLASS}
  image:
    imagePullPolicy: IfNotPresent
  node:
    replicas: ${WFPS_REPLICAS}
    resources:
      limits:
        cpu: ${WFPS_LIMITS_CPU}
        memory: ${WFPS_LIMITS_MEMORY}
      requests:
        cpu: ${WFPS_REQS_CPU}
        memory: ${WFPS_REQS_MEMORY}
    logging:
      maxFileSize: 50
      consoleFormat: json
      consoleSource: 'message,trace,accessLog,ffdc,audit'
      maxFiles: 10
      enableFilebeat: false
      consoleLogLevel: INFO
      traceFormat: ENHANCED
      messageFormat: simple
      traceSpecification: '${WFPS_TRACE_LEVEL}'
    processAppsLogging:
      baseFilePath: /logs/process-apps
      customProcessAppsLogPVC: ''
      customProcessAppsLogPVCSize: 1Gi
      defaultLogName: ProcessApps.log
      enableGlobal: false
      logFileSize: 80
      logNumberOfRollovers: 5
  database:
    external:
      serverName: ${WFPS_EXT_DB_SERVER}
      port: ${WFPS_EXT_DB_PORT}
      type: postgresql
      databaseName:	${WFPS_EXT_DB_NAME}
      current_schema: wfpsdb
      dbCredentialSecret:	${WFPS_EXT_DB_CREDENTIAL_SECRET} # The secret key must include the username and password      
      enableSSL: ${WFPS_EXT_DB_ENABLE_SSL}
      dbServerCertSecret: ${WFPS_EXT_DB_CERT_SSL}
      sslMode: require
    client:
      maxConnectionPoolSize: ${WFPS_EXT_DB_CONN_POOL_MAX}
      minConnectionPoolSize: ${WFPS_EXT_DB_CONN_POOL_MIN}
