/* 
Db WfPS 2
*/
DROP DATABASE IF EXISTS wfpsdb2;
CREATE DATABASE wfpsdb2;
CREATE ROLE wfps_user PASSWORD 'dem0s' CREATEDB CREATEROLE INHERIT LOGIN;
GRANT CONNECT ON DATABASE wfps_user TO public;
ALTER DATABASE wfpsdb2 OWNER TO wfps_user;
GRANT ALL PRIVILEGES ON DATABASE wfpsdb2 TO wfps_user;
CREATE SCHEMA wfpsdb2;
ALTER SCHEMA wfpsdb2 OWNER TO wfps_user;
GRANT ALL ON SCHEMA wfpsdb2 TO wfps_user;
ALTER DATABASE wfpsdb2 SET timezone TO 'Etc/UTC';
