/* 
Db WfPS 4
*/
DROP DATABASE IF EXISTS wfpsdb4;
CREATE DATABASE wfpsdb4;
CREATE ROLE wfps_user PASSWORD 'dem0s' CREATEDB CREATEROLE INHERIT LOGIN;
GRANT CONNECT ON DATABASE wfps_user TO public;
ALTER DATABASE wfpsdb4 OWNER TO wfps_user;
GRANT ALL PRIVILEGES ON DATABASE wfpsdb4 TO wfps_user;
CREATE SCHEMA wfpsdb4;
ALTER SCHEMA wfpsdb4 OWNER TO wfps_user;
GRANT ALL ON SCHEMA wfpsdb4 TO wfps_user;
ALTER DATABASE wfpsdb4 SET timezone TO 'Etc/UTC';
