/* 
Db WfPS 3
*/
DROP DATABASE IF EXISTS wfpsdb3;
CREATE DATABASE wfpsdb3;
CREATE ROLE wfps_user PASSWORD 'dem0s' CREATEDB CREATEROLE INHERIT LOGIN;
GRANT CONNECT ON DATABASE wfps_user TO public;
ALTER DATABASE wfpsdb3 OWNER TO wfps_user;
GRANT ALL PRIVILEGES ON DATABASE wfpsdb3 TO wfps_user;
CREATE SCHEMA wfpsdb3;
ALTER SCHEMA wfpsdb3 OWNER TO wfps_user;
GRANT ALL ON SCHEMA wfpsdb3 TO wfps_user;
ALTER DATABASE wfpsdb3 SET timezone TO 'Etc/UTC';

