/* 
Db WfPS 1
*/
DROP DATABASE IF EXISTS wfpsdb1;
CREATE DATABASE wfpsdb1;
CREATE ROLE wfps_user PASSWORD 'dem0s' CREATEDB CREATEROLE INHERIT LOGIN;
GRANT CONNECT ON DATABASE wfps_user TO public;
ALTER DATABASE wfpsdb1 OWNER TO wfps_user;
GRANT ALL PRIVILEGES ON DATABASE wfpsdb1 TO wfps_user;
CREATE SCHEMA wfpsdb1;
ALTER SCHEMA wfpsdb1 OWNER TO wfps_user;
GRANT ALL ON SCHEMA wfpsdb1 TO wfps_user;
ALTER DATABASE wfpsdb1 SET timezone TO 'Etc/UTC';

