/* 
Db WfPS 5
*/
DROP DATABASE IF EXISTS wfpsdb5;
CREATE DATABASE wfpsdb5;
CREATE ROLE wfps_user PASSWORD 'dem0s' CREATEDB CREATEROLE INHERIT LOGIN;
GRANT CONNECT ON DATABASE wfps_user TO public;
ALTER DATABASE wfpsdb5 OWNER TO wfps_user;
GRANT ALL PRIVILEGES ON DATABASE wfpsdb5 TO wfps_user;
CREATE SCHEMA wfpsdb5;
ALTER SCHEMA wfpsdb5 OWNER TO wfps_user;
GRANT ALL ON SCHEMA wfpsdb5 TO wfps_user;
ALTER DATABASE wfpsdb5 SET timezone TO 'Etc/UTC';

