export WFPS_NAME=wfps-demo-1
export WFPS_NAMESPACE=cp4ba-wfps-production
export WFPS_STORAGE_CLASS="ocs-external-storagecluster-cephfs"
export WFPS_STORAGE_CLASS_BLOCK="ocs-external-storagecluster-ceph-rbd"
export WFPS_APP_VER=25.0.1
export WFPS_APP_TAG=${WFPS_APP_VER}
export WFPS_FEDERATE=false
export WFPS_ADMINUSER=cp4admin
export WFPS_ADMINPASSWORD=dem0s

export WFPS_LIMITS_CPU=3000m
export WFPS_LIMITS_MEMORY=3072Mi
export WFPS_REQS_CPU=500m
export WFPS_REQS_MEMORY=1024Mi

export WFPS_EXT_DB_SERVICE_NAME="my-postgres-1-for-cp4ba-rw"
export WFPS_EXT_DB_SERVER="${WFPS_EXT_DB_SERVICE_NAME}.${WFPS_NAMESPACE}.svc.cluster.local"
export WFPS_EXT_DB_PORT=5432
export WFPS_EXT_DB_NAME="wfpsdb1"
export WFPS_EXT_DB_CREDENTIAL_SECRET=wfpsdb-secret
export WFPS_EXT_DB_USER_NAME="wfps_user"
export WFPS_EXT_DB_USER_PASSWORD="dem0s"


export WFPS_FEDERATE_TEXTSEARCH=false
export WFPS_FEDERATE_TEXTSEARCH_SIZE="10Gi"
export WFPS_FEDERATE_TEXTSEARCHSIZE_SNAP="2Gi"
