# WfPS server name
export WFPS_NAME="wfps-demo-3"
export WFPS_RUNTIME_TEMPLATE="../templates25.0.1/wfps-cr-ext-db.yaml"

# WfPS license type: non-production | production
export WFPS_LICENSE_TYPE="non-production"

# WfPS target environment
export WFPS_NAMESPACE=${CP4BA_INST_NAMESPACE}
export WFPS_STORAGE_CLASS=${CP4BA_INST_SC_FILE}
export WFPS_STORAGE_CLASS_BLOCK=${CP4BA_INST_SC_BLOCK}
export WFPS_APP_VER=${CP4BA_INST_APPVER}
export WFPS_APP_TAG=${WFPS_APP_VER}

# WfPS admin user credentials
export WFPS_ADMINUSER=${CP4BA_INST_PAKBA_ADMIN_USER}
export WFPS_ADMINPASSWORD=${CP4BA_INST_PAKBA_ADMIN_PWD}

# WfPS resources
export WFPS_LIMITS_CPU=3000m
export WFPS_LIMITS_MEMORY=3072Mi
export WFPS_REQS_CPU=500m
export WFPS_REQS_MEMORY=1024Mi

# WfPS trusted certificates (list of comma separated secret 'names' containing TLS certificates)
# example (keep single quotas for each name): WFPS_TLS_SECRET_NAMES="'secret-name-1','secret-name-2'"
export WFPS_TLS_SECRET_NAMES=""

# WfPS database (must be one in .sql statements file references by CP4BA_INST_DB_1_TEMPLATE)
export WFPS_EXT_DB_NAME="wfpsdb3"
export WFPS_EXT_DB_TEMPLATE="../templates-sql/db-statements-wfps3.sql"
export WFPS_EXT_DB_USER_NAME="wfps_user"
export WFPS_EXT_DB_USER_PASSWORD="dem0s"
export WFPS_EXT_DB_SERVER="${CP4BA_INST_DB_1_SERVER_NAME}"
export WFPS_EXT_DB_PORT=${CP4BA_INST_DB_SERVER_PORT}
export WFPS_EXT_DB_CREDENTIAL_SECRET="${WFPS_EXT_DB_NAME}-secret"
export WFPS_EXT_DB_CONN_POOL_MIN=50
export WFPS_EXT_DB_CONN_POOL_MAX=200

# WfPS PFS federation
export WFPS_FEDERATE=true
export WFPS_FEDERATE_TEXTSEARCH=${WFPS_FEDERATE}
export WFPS_FEDERATE_TEXTSEARCH_SIZE="10Gi"
export WFPS_FEDERATE_TEXTSEARCHSIZE_SNAP="2Gi"
